spring:
  application:
    name: pet-helper-user-service
#  redis:
#    port: 6379
#    host: localhost
#    cluster:
#      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Users
      uri: mongodb://root:root@localhost:27017/Users?authSource=admin&retryWrites=true&w=majority